export interface SubBlockData {
  id: string;
  type: string;
  props: Record<string, unknown>;
  sortOrder: number;
}

export const BLOCK_TYPES = {
  hero_video: {
    label: "Hero (Video)",
    icon: "Video",
    description: "Video background with overlay text and CTA",
    defaultProps: {
      videoUrl: "",
      posterImageUrl: "",
      tagline: "",
      heading: "",
      subheading: "",
      ctaText: "",
      ctaUrl: "",
      ctaText2: "",
      ctaUrl2: "",
      overlayOpacity: 0.5,
      showStats: true,
      scrollHintText: "Scroll",
    },
  },
  hero_image: {
    label: "Hero (Image)",
    icon: "Image",
    description: "Image background with overlay text and CTA",
    defaultProps: {
      imageUrl: "",
      heading: "",
      subheading: "",
      ctaText: "",
      ctaUrl: "",
      overlayOpacity: 0.4,
      backgroundColor: "#1A2640",
      textColor: "#ffffff",
      height: "70vh",
    },
  },
  text_section: {
    label: "Text Section",
    icon: "Type",
    description: "Rich text content area",
    defaultProps: {
      content: "",
      maxWidth: "4xl",
      backgroundColor: "transparent",
      textColor: "",
      paddingY: "md",
    },
  },
  logo_gallery: {
    label: "Logo Gallery",
    icon: "Grid3X3",
    description: "Grid of logos or images",
    defaultProps: {
      heading: "",
      headingColor: "",
      headingFont: "",
      logos: [] as { imageUrl: string; alt: string; url?: string }[],
      columns: 4,
      grayscale: true,
      backgroundColor: "",
    },
  },
  stats: {
    label: "Stats",
    icon: "BarChart3",
    description: "Number cards in a row",
    defaultProps: {
      heading: "",
      headingFont: "",
      stats: [] as { value: string; label: string }[],
      backgroundColor: "#1A2640",
      textColor: "#ffffff",
      statValueColor: "#E8D5B0",
      statValueFont: "",
      statLabelColor: "#ffffff59",
      statLabelFont: "",
    },
  },
  cta_banner: {
    label: "CTA Banner",
    icon: "Megaphone",
    description: "Full-width call to action",
    defaultProps: {
      heading: "",
      headingFont: "",
      text: "",
      textFont: "",
      ctaText: "",
      ctaUrl: "",
      ctaButtonFont: "",
      backgroundColor: "#B07D3A",
      headingColor: "#ffffff",
      textColor: "#ffffffaa",
      ctaButtonColor: "#1A2640",
      ctaButtonTextColor: "#ffffff",
    },
  },
  two_column: {
    label: "Two Column",
    icon: "Columns2",
    description: "Side-by-side content areas",
    defaultProps: {
      leftContent: "",
      rightContent: "",
      leftWidth: "1/2",
      leftBlocks: [] as SubBlockData[],
      rightBlocks: [] as SubBlockData[],
    },
  },
  contact_form: {
    label: "Contact Form",
    icon: "Mail",
    description: "Name, email, and message form",
    defaultProps: {
      heading: "Get in Touch",
      headingFont: "",
      description: "",
      descriptionFont: "",
      showAddress: true,
      showEmail: true,
      headingColor: "",
      descriptionColor: "#888780",
      backgroundColor: "#F5F3EE",
      buttonColor: "#B07D3A",
      buttonTextColor: "#1A2640",
    },
  },
  newsletter_signup: {
    label: "Newsletter Signup",
    icon: "Newspaper",
    description: "Email signup form",
    defaultProps: {
      heading: "Stay Updated",
      headingFont: "",
      description: "",
      descriptionFont: "",
      backgroundColor: "#1A2640",
      headingColor: "#ffffff",
      descriptionColor: "#ffffff99",
      buttonColor: "#B07D3A",
      buttonTextColor: "#1A2640",
    },
  },
  quote: {
    label: "Quote",
    icon: "Quote",
    description: "Blockquote with attribution",
    defaultProps: {
      text: "",
      quoteFont: "",
      attribution: "",
      attributionFont: "",
      role: "",
      roleFont: "",
      quoteColor: "#1A2640e6",
      attributionColor: "#1A2640",
      roleColor: "#888780",
      backgroundColor: "",
    },
  },
  image: {
    label: "Image",
    icon: "ImageIcon",
    description: "Single image with caption",
    defaultProps: {
      imageUrl: "",
      alt: "",
      caption: "",
      captionFont: "",
      captionColor: "#6b7280",
      maxWidth: "4xl",
    },
  },
  embed: {
    label: "Video Embed",
    icon: "Play",
    description: "YouTube or Vimeo embed",
    defaultProps: {
      url: "",
      title: "",
      aspectRatio: "16/9",
    },
  },
  spacer: {
    label: "Spacer",
    icon: "Minus",
    description: "Vertical space",
    defaultProps: {
      height: "md",
    },
  },
  asset_cards: {
    label: "Asset Cards",
    icon: "Grid3X3",
    description: "Grid of asset class cards with hover effects",
    defaultProps: {
      tagline: "",
      taglineFont: "",
      heading: "",
      headingFont: "",
      subtitle: "",
      subtitleFont: "",
      cards: [] as { name: string; description: string }[],
      backgroundColor: "#F5F3EE",
      taglineColor: "",
      headingColor: "",
      subtitleColor: "",
    },
  },
  philosophy: {
    label: "Philosophy",
    icon: "Quote",
    description: "Quote with pillars sidebar",
    defaultProps: {
      tagline: "",
      taglineFont: "",
      quote: "",
      quoteFont: "",
      attribution: "",
      attributionFont: "",
      pillars: [] as { name: string; description: string }[],
      backgroundColor: "#1A2640",
      taglineColor: "",
      quoteColor: "#ffffffe6",
      attributionColor: "#ffffff4d",
      pillarNameColor: "#E8D5B0",
      pillarNameFont: "",
      pillarDescColor: "#ffffff66",
      pillarDescFont: "",
    },
  },
  process_steps: {
    label: "Process Steps",
    icon: "ListOrdered",
    description: "Numbered steps with sidebar card",
    defaultProps: {
      tagline: "",
      heading: "",
      headingFont: "",
      steps: [] as { name: string; description: string }[],
      sidebarTagline: "",
      sidebarStat: "",
      sidebarLabel: "",
      sidebarQuote: "",
      showDynamicStats: false,
      backgroundColor: "#ffffff",
      headingColor: "",
      stepNameColor: "#1A2640",
      stepNameFont: "",
      stepDescColor: "#888780",
      stepDescFont: "",
      sidebarBgColor: "#1A2640",
    },
  },
  cta_split: {
    label: "CTA Split",
    icon: "Columns2",
    description: "Two-column CTA with bullet points",
    defaultProps: {
      tagline: "",
      heading: "",
      headingFont: "",
      description: "",
      descriptionFont: "",
      ctaText: "",
      ctaUrl: "",
      ctaText2: "",
      ctaUrl2: "",
      bullets: [] as { text: string }[],
      bulletFont: "",
      backgroundColor: "#F5F3EE",
      headingColor: "",
      descriptionColor: "#888780",
      bulletColor: "#1A1A18",
      ctaButtonColor: "#B07D3A",
      ctaButtonTextColor: "#1A2640",
    },
  },
} as const;

export type BlockType = keyof typeof BLOCK_TYPES;

export interface PageBlockData {
  id?: string;
  type: BlockType;
  props: Record<string, unknown>;
  sortOrder: number;
  mediaId?: string | null;
}

/** Block types allowed inside Two Column sub-blocks (no heroes, no nested two_column) */
export const NESTABLE_BLOCK_TYPES: BlockType[] = (
  Object.keys(BLOCK_TYPES) as BlockType[]
).filter((t) => !["hero_video", "hero_image", "two_column"].includes(t));
