-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('DOCUMENT_UPLOADED', 'DISTRIBUTION_RECEIVED', 'CAPITAL_CALL', 'INVESTMENT_UPDATE', 'ADVISOR_INVITED', 'ADVISOR_ACCEPTED', 'SUPPORT_TICKET', 'SYSTEM_MESSAGE', 'ACTIVITY_POST') NOT NULL;
